version: '3.8'

services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: vendas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vendas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vendas-network

  # Serviço para pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9000:80"
    networks:
      - vendas-network

  # Serviço para a aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vendas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - vendas-network

# Definindo redes e volumes
networks:
  vendas-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
